from datetime import datetime, timezone

from flask_sqlalchemy import SQLAlchemy


# SQLAlchemy is created here and initialized inside the application factory.
db = SQLAlchemy()


def utc_now() -> datetime:
    """Return a timezone-aware UTC timestamp for database defaults."""

    return datetime.now(timezone.utc)


class Endpoint(db.Model):
    """Registered endpoint managed by SOC Sentinel agents."""

    __tablename__ = "endpoints"

    id = db.Column(db.Integer, primary_key=True)
    endpoint_id = db.Column(db.String(20), unique=True, nullable=False, index=True)
    hostname = db.Column(db.String(120), nullable=False)
    username = db.Column(db.String(120), nullable=True)
    operating_system = db.Column(db.String(120), nullable=True)
    os_version = db.Column(db.String(80), nullable=True)
    ip_address = db.Column(db.String(45), nullable=True)
    mac_address = db.Column(db.String(64), nullable=True)
    agent_version = db.Column(db.String(40), nullable=True)
    device_fingerprint = db.Column(db.String(64), nullable=True, index=True)
    identity_status = db.Column(db.String(30), nullable=False, default="Unknown", index=True)
    identity_previous_fingerprint = db.Column(db.String(64), nullable=True)
    identity_observed_fingerprint = db.Column(db.String(64), nullable=True)
    identity_last_changed = db.Column(db.DateTime(timezone=True), nullable=True)
    api_key = db.Column(db.String(128), unique=True, nullable=False, index=True)
    status = db.Column(db.String(30), nullable=False, default="Offline", index=True)
    registered_at = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)
    last_seen = db.Column(db.DateTime(timezone=True), nullable=True, index=True)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)
    updated_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

    def __repr__(self) -> str:
        return f"<Endpoint {self.endpoint_id} {self.hostname}>"


class Alert(db.Model):
    """Security alert generated by the detection engine."""

    __tablename__ = "alerts"

    id = db.Column(db.Integer, primary_key=True)
    alert_id = db.Column(db.String(24), unique=True, nullable=False, index=True)
    endpoint_id = db.Column(db.String(20), nullable=False, index=True)
    rule_id = db.Column(db.String(80), nullable=False, index=True)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, nullable=False)
    severity = db.Column(db.String(30), nullable=False, default="low")
    timestamp = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)
    status = db.Column(db.String(30), nullable=False, default="Open", index=True)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)

    def __repr__(self) -> str:
        return f"<Alert {self.alert_id} {self.title}>"


class DetectionRule(db.Model):
    """Configurable detection rule metadata."""

    __tablename__ = "detection_rules"

    id = db.Column(db.Integer, primary_key=True)
    rule_id = db.Column(db.String(80), unique=True, nullable=False, index=True)
    name = db.Column(db.String(160), nullable=False)
    description = db.Column(db.Text, nullable=False)
    severity = db.Column(db.String(30), nullable=False)
    enabled = db.Column(db.Boolean, nullable=False, default=True, index=True)
    threshold = db.Column(db.Integer, nullable=False, default=1)
    time_window = db.Column(db.Integer, nullable=False, default=0)
    mitre_tactic = db.Column(db.String(120), nullable=True)
    mitre_technique = db.Column(db.String(120), nullable=True)

    def __repr__(self) -> str:
        return f"<DetectionRule {self.rule_id} {self.name}>"


class CorrelationRule(db.Model):
    """Configurable correlation rule metadata."""

    __tablename__ = "correlation_rules"

    id = db.Column(db.Integer, primary_key=True)
    rule_id = db.Column(db.String(80), unique=True, nullable=False, index=True)
    name = db.Column(db.String(160), nullable=False)
    description = db.Column(db.Text, nullable=False)
    enabled = db.Column(db.Boolean, nullable=False, default=True, index=True)
    severity = db.Column(db.String(30), nullable=False)
    time_window = db.Column(db.Integer, nullable=False, default=0)
    mitre_tactic = db.Column(db.String(120), nullable=True)
    mitre_technique = db.Column(db.String(120), nullable=True)
    version = db.Column(db.String(20), nullable=False, default="1.0")
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)
    updated_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

    def __repr__(self) -> str:
        return f"<CorrelationRule {self.rule_id} {self.name}>"


class CorrelatedIncident(db.Model):
    """Incident created by correlating multiple security alerts."""

    __tablename__ = "correlated_incidents"

    id = db.Column(db.Integer, primary_key=True)
    incident_id = db.Column(db.String(24), unique=True, nullable=False, index=True)
    endpoint_id = db.Column(db.String(20), nullable=False, index=True)
    correlation_rule_id = db.Column(db.String(80), nullable=False, index=True)
    severity = db.Column(db.String(30), nullable=False, index=True)
    status = db.Column(db.String(30), nullable=False, default="OPEN", index=True)
    title = db.Column(db.String(200), nullable=False, default="Correlated Incident")
    summary = db.Column(db.Text, nullable=False)
    confidence = db.Column(db.Integer, nullable=False, default=0)
    risk_score = db.Column(db.Integer, nullable=False, default=0)
    assigned_to = db.Column(db.String(120), nullable=True, index=True)
    priority = db.Column(db.String(30), nullable=False, default="Medium", index=True)
    mitre_tactic = db.Column(db.String(120), nullable=True)
    mitre_technique = db.Column(db.String(120), nullable=True)
    timeline = db.Column(db.JSON, nullable=False, default=list)
    matched_alert_ids = db.Column(db.JSON, nullable=False, default=list)
    evidence = db.Column(db.JSON, nullable=False, default=list)
    evidence_hash = db.Column(db.String(64), nullable=False, default="", index=True)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)
    resolved_at = db.Column(db.DateTime(timezone=True), nullable=True)
    closed_at = db.Column(db.DateTime(timezone=True), nullable=True)
    updated_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

    def __repr__(self) -> str:
        return f"<CorrelatedIncident {self.incident_id} {self.status}>"


class IncidentNote(db.Model):
    """Analyst investigation note attached to a correlated incident."""

    __tablename__ = "incident_notes"

    id = db.Column(db.Integer, primary_key=True)
    incident_id = db.Column(db.String(24), nullable=False, index=True)
    author = db.Column(db.String(120), nullable=False, default="Analyst")
    note = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)
    updated_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

    def __repr__(self) -> str:
        return f"<IncidentNote {self.incident_id} {self.author}>"


class IncidentHistory(db.Model):
    """Auditable workflow event for an incident investigation."""

    __tablename__ = "incident_history"

    id = db.Column(db.Integer, primary_key=True)
    incident_id = db.Column(db.String(24), nullable=False, index=True)
    action = db.Column(db.String(120), nullable=False)
    previous_status = db.Column(db.String(30), nullable=True)
    new_status = db.Column(db.String(30), nullable=True)
    actor = db.Column(db.String(120), nullable=False, default="Analyst")
    timestamp = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)

    def __repr__(self) -> str:
        return f"<IncidentHistory {self.incident_id} {self.action}>"


class EndpointCommand(db.Model):
    """Manual safe-response command queued for an endpoint agent."""

    __tablename__ = "endpoint_commands"

    id = db.Column(db.Integer, primary_key=True)
    command_id = db.Column(db.String(24), unique=True, nullable=False, index=True)
    endpoint_id = db.Column(db.String(20), nullable=False, index=True)
    command_type = db.Column(db.String(80), nullable=False, index=True)
    command_payload = db.Column(db.JSON, nullable=False, default=dict)
    status = db.Column(db.String(30), nullable=False, default="PENDING", index=True)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, default=utc_now)
    started_at = db.Column(db.DateTime(timezone=True), nullable=True)
    completed_at = db.Column(db.DateTime(timezone=True), nullable=True)
    requested_by = db.Column(db.String(120), nullable=False, default="Analyst")
    response = db.Column(db.JSON, nullable=True)
    error_message = db.Column(db.Text, nullable=True)

    def __repr__(self) -> str:
        return f"<EndpointCommand {self.command_id} {self.status}>"


class Telemetry(db.Model):
    """Raw security telemetry received from endpoint agents."""

    __tablename__ = "telemetry"

    id = db.Column(db.Integer, primary_key=True)
    endpoint_id = db.Column(db.String(20), nullable=False, index=True)
    collector = db.Column(db.String(60), nullable=False, index=True)
    event_type = db.Column(db.String(120), nullable=False, index=True)
    severity = db.Column(db.String(30), nullable=False, default="info", index=True)
    timestamp = db.Column(db.DateTime(timezone=True), nullable=False, index=True)
    raw_data = db.Column(db.JSON, nullable=False)
    processed = db.Column(db.Boolean, nullable=False, default=False, index=True)

    def __repr__(self) -> str:
        return f"<Telemetry {self.endpoint_id} {self.collector} {self.event_type}>"


class Setting(db.Model):
    """Editable SOC Sentinel configuration stored in the database."""

    __tablename__ = "settings"

    id = db.Column(db.Integer, primary_key=True)
    key = db.Column(db.String(120), unique=True, nullable=False, index=True)
    value = db.Column(db.String(500), nullable=False)
    label = db.Column(db.String(160), nullable=False)
    category = db.Column(db.String(80), nullable=False, index=True)
    value_type = db.Column(db.String(30), nullable=False, default="text")
    description = db.Column(db.Text, nullable=True)
    updated_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

    def __repr__(self) -> str:
        return f"<Setting {self.key}>"
